### ISSUE TITLE
Error when handling commented .htaccess files

### ISSUE THREAD

**Issue by RafaelOlivra** [e404/htaccess-for-nginx#14]
I found out I was getting 500 errors while running WordPress on my local dev.
After some debugging I managed to isolate the error: it turns out that the Lua script is concatenating all .htaccess  files before processing them, but if one of the .htacess files ends with a comment, then the first line of the next concatenated .htaccess   file will be ignored, example:

.htaccess in the root / : 
```
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```
.htaccess in the wp-content/themes/example/.htaccess  : 
```
<Files "style.css">  
  Order Allow,Deny
  Deny from all
</Files>
```

For some reason the processed htaccess variable (See line 220 of the htaccess.lua) would produce the following string, note that <Files ... should have been parsed in a new line:
```
...
# END WordPress<Files "style.css">
...
```

This would cause the line to be ignored since it starts with a #, and then produce a syntax error ".htaccess syntax error: Closing ``</file>`` without opening tag".

I managed to easily fix this issue by appending a .."\n" to each new file during the concatenation process (See line 220 of the htaccess.lua):

```
htaccess = C_DIR..' '..relative_dir..'\n'..htaccess..current_htaccess..'\n'
```

It worked for me, but perhaps you may want to look into it and write a proper solution.

Thanks for the amazing work!

**Comment by e404** [comment]
Hi @RafaelOlivra,

thanks a lot for your detailed issue description and also providing a fix.
Would you mind submitting a Pull Request with the change?
I'm gonna merge it right away.
