### ISSUE TITLE
 unexpected symbol near '<'

### ISSUE THREAD

**Issue by razzerar** [e404/htaccess-for-nginx#15]
hi 

I am trying to install ther htaccess for Nginx on my VM but i get the following error in ubuntu 22.04.

root@ubuntu-instance1:~# luajit -b htaccess.lua /etc/nginx/lua/htaccess.lbc
luajit: htaccess.lua:8: unexpected symbol near '<'
root@ubuntu-instance1:~#

**Comment by rkaiser0324** [comment]
That character isn't in the file `htaccess.lua` at all - can you attach that file?  Maybe your repo is dirty.
