### ISSUE TITLE
nil value

### ISSUE THREAD

**Issue by HaziFlorinMarian** [e404/htaccess-for-nginx#4]
Error:
`2021/07/31 15:06:07 [error] 6986#100966: *485 lua entry thread aborted: runtime error: /usr/local/etc/nginx/htaccess.lua:1214: attempt to concatenate local 'new_qs' (a nil value)`

.htaccess which generated this:
`### BEGIN - WHMCS managed rules - DO NOT EDIT BETWEEN WHMCS MARKERS ###
<IfModule mod_rewrite.c>
RewriteEngine on

RewriteRule ^utilizarea-acceptabila/			utilizare_acceptabila.php
RewriteRule ^utilizarea-acceptabila				utilizare_acceptabila.php

RewriteRule ^politica-de-confidentialitate/		politica_de_confidentialitate.php
RewriteRule ^politica-de-confidentialitate		politica_de_confidentialitate.php

RewriteRule ^termeni-si-conditii/		terms_and_conditions.php
RewriteRule ^termeni-si-conditii		terms_and_conditions.php

RewriteRule ^trial/		cart.php?gid=9
RewriteRule ^trial		cart.php?gid=9

RewriteRule ^vps-game/		vps-hosting-game.php
RewriteRule ^vps-game		vps-hosting-game.php

RewriteRule ^gazduire-radio/	gazduire-radio.php
RewriteRule ^gazduire-radio		gazduire-radio.php

RewriteRule ^vps-ssd/		vps-hosting-ssd.php
RewriteRule ^vps-ssd		vps-hosting-ssd.php

RewriteRule ^vps-hdd/		vps-hosting-hdd.php
RewriteRule ^vps-hdd		vps-hosting-hdd.php

RewriteRule ^gazduire-ssd/	web-hosting-ssd.php
RewriteRule ^gazduire-ssd	web-hosting-ssd.php

RewriteRule ^gazduire-hdd/	web-hosting-hdd.php
RewriteRule ^gazduire-hdd	web-hosting-hdd.php

RewriteRule ^register-domain/		cart.php?a=add&domain=register
RewriteRule ^register-domain		cart.php?a=add&domain=register

RewriteRule ^transfer-domain/		cart.php?a=add&domain=transfer
RewriteRule ^transfer-domain		cart.php?a=add&domain=transfer

# RewriteBase is set to "/" so rules do not need updating if the
# installation directory is relocated.  It is imperative that
# there is also a RewriteCond rule later that can effectively get
# the actual value by comparison against the request URI.
# 
# If there are _any_ other RewriteBase directives in this file,
# the last entry will take precedence!
RewriteBase /

# Redirect directories to an address with slash
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^(.+[^/])$  $1/ [R]

# Send all remaining (routable paths) through index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Determine and use the actual base
RewriteCond $0#%{REQUEST_URI} ([^#]*)#(.*)\1$
RewriteRule ^.*$ %2index.php [QSA,L]
</IfModule>
### END - WHMCS managed rules - DO NOT EDIT BETWEEN WHMCS MARKERS ###`

nginx version: nginx/1.20.1

Thank you!

**Comment by myrandor** [comment]
I don't know if it could help, but I changed line 776 and 777 which are this:
`		elseif whitelist[svar] then
			replace = ngx.var[svar]
`

for this:
`		elseif whitelist[svar] then
			if ngx.var[svar] == nil then
				replace = ''
			else
				replace = ngx.var[svar]
			end
`
