### ISSUE TITLE
Error when trying to run htaccess for nginx, nginx says unknown directive: rewrite_by_lua_file

### ISSUE THREAD

**Issue by rhys19** [e404/htaccess-for-nginx#5]
nginx: [emerg] unknown directive "rewrite_by_lua_file" in /etc/nginx/sites-enabled/domain.com.conf:6
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by rkaiser0324** [comment]
It sounds like you don't have the Lua module installed into nginx.  Check the README for details.
