### ISSUE TITLE
Doesn't work with Laravel .htaccess

### ISSUE THREAD

**Issue by benyaminl** [e404/htaccess-for-nginx#7]
Uhm, Hello, I tried htaccess.lua with laravel .htaccess :

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Send Requests To Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

```

Is there anything I can do about it? Thank you. 

I tried default htaccess test file 
```
Order deny,allow  
Deny from all
```

It works fine with openresty/nginx 1.19.9 on Windows with luajit. Any help is appreciated, thank you

**Comment by e404** [comment]
Like @rkaiser0324 clarified in the Readme, the E flag is unsupported.
The script is designed so that whenever an unsupported directive or feature is used, access is denied to prevent unintended access.
