### ISSUE TITLE
We are getting this error message while building lua htaccess module. 

### ISSUE THREAD

**Issue by securewebsite** [e404/htaccess-for-nginx#8]
[error] 11#11: *4 lua entry thread aborted: runtime error: /etc/nginx/lua/htaccess.lua:893: bad argument #1 to 'match' (string expected, got nil)

**Comment by rkaiser0324** [comment]
I assume you are not getting this error at compilation time, but at runtime.  If so please provide the `.htaccess` file you are using.

**Comment by e404** [comment]
No further activity, closing the issue
